---
title: "Fallstudie zur Vorlesung Multivariate Methoden"
subtitle: "Herleitung von Profilen deutscher Kreise und Städte"
author: "Prof. Dr. Michael Bücker, Niels Schlüsener"
date: "13.10.2022"
papersize: a4
output:
  pdf_document: 
    latex_engine: xelatex
    fig_caption: false
  html_document:
    df_print: paged
---


## Kontext

In der rasanten Dynamik des 21. Jahrhunderts sind Städte und Gemeinden konfrontiert mit immer komplexeren Herausforderungen. Eine effiziente und nachhaltige Stadtentwicklung verlangt heute mehr denn je ein fundiertes Verständnis für die vielen Variablen, die unsere Lebensräume prägen. In dieser Hinsicht bietet die Clusteranalyse ein geeignetes Werkzeug, um strukturelle Muster und Trends aufzudecken. Die Ausschreibung richtet sich auf eine detaillierte Analyse sämtlicher Kreise und Städte in Deutschland, basierend auf Daten, die unterschiedliche Aspekte der Infrastrukturnutzung in städtischen und ländlichen Gebieten, sowie der landwirtschaftlichen Bodennutzung erfassen.


Im Zuge dieser Untersuchung hat der in Deutschland zuständige Verband für städtische Entwicklung Ihrem Team den Auftrag erteilt, einen aktuellen Überblick über die spezifischen Gegebenheiten und Herausforderungen der Kreise und Städte in Deutschland zu erstellen. Dieser Überblick soll als Grundlage für zukünftige Strategien zur Verbesserung der Lebensqualität und der nachhaltigen Entwicklung dienen. Hierfür steht Ihnen ein umfangreicher Datensatz zur Verfügung, der Daten aus allen Kreisen und Städten in Deutschland umfasst.

Mithilfe dieser Daten und den im Rahmen der Studie vorgestellten Analysemethoden sind Sie nun beauftragt, Profile der einzelnen Kreise und Städte zu erstellen. Dabei sollen die Kreise und Städte hinsichtlich ihrer unterschiedlichen Merkmale geclustert werden. Dies wird ein tiefergehendes Verständnis der einzigartigen Gegebenheiten und Herausforderungen in jedem Bezirk ermöglichen und so die Grundlage für evidenzbasierte Strategien zur Verbesserung der Lebensqualität in den Regionen schaffen.

## Daten 

In ILIAS finden Sie die Datei `regional_daten_de`.RData`. Diese enthält Daten von 537 deutschen Kreisen und kreisfreie Städten. Zu den betrachteten Dimensionen zählen Ackerfläche, Beschäftigte (insbesondere Niederlassungen und verschiedene Betriebsgrößen), die Verteilung der Bodenfläche, die Wahlbeteiligung, Tourismusdaten und die Siedlungsfläche.

\newpage

## Aufgabenstellung

Ziel dieser Fallstudie ist, zunächst aus den 69 Attributen eine geringere Anzahl Dimensionen mit Hilfe von Methoden zur Dimensionsreduktion abzuleiten, die anschließend zur Bestimmung der Profile mit Hilfe einer Clusteranalyse genutzt werden können. Außerdem können vorab Dimensionen ausgeschlossen werden wenn sie anhand von inhaltlicher Kriterien
nicht weiter zur Analyse genutzt werden sollen.

Die konkreten Analyseschritte, welche Sie zur Lösung der Aufgabenstellung in \textbf{\textsf{R}} lösen sollen, lauten wie folgt:

1.	Verschaffen Sie sich einen Überblick und ein Verständnis der vorliegenden Daten durch deskriptive Analysen und grafische Darstellungen.
2.	Reduzieren Sie die Anzahl der Dimensionen mit Methoden der Dimensionsreduktion. Sie sollten dabei nicht mehr als zehn Dimensionen extrahieren. Eine Interpretation der Dimensionen ist nicht zwingend notwendig.
3.	Nutzen Sie Ihre neuen Dimensionen als Basis, um mit Hilfe einer Clusteranalyse Profile der Gemeinden herzuleiten. Sie sollten nicht mehr als zehn Profile herausarbeiten. Kennzeichnen Sie ihre endgültige Lösung. 
4.	Interpretieren und beschreiben Sie die gebildeten Cluster. Entwickeln Sie außerdem Empfehlungen auf Basis der Profile, wie die Gemeinden innerhalb der Profile ihr Abfallmanagement verbessern könnten.

## Format

Ihre Abgabe besteht aus drei Teilen:

### R Code

Geben Sie den von Ihnen erstellten R Code zur Datenanalyse, Dimensionsreduktion und Clustererstellung ab. Der Code sollte nur die relevanten Teile enthalten, welche die Ergebnisse in Ihrer Präsentation erzeugen. Stellen Sie sicher, dass der Code sauber, nachvollziehbar, gut dokumentiert und vor allem auch lauffähig ist. Die aus dem Code resultierenden Ergebnisse sollten denen in Ihrem Bericht entsprechen!

### Management-Präsentation

Erstellen Sie zusätzlich zum `*.R` Skript eine Management-Präsentation, in der Ihre Ergebnisse dokumentiert werden. Diese Präsentation sollte maximal 8 Folien enthalten (+ je eine pro ermitteltes Profil) und Ihre Vorgehensweise und die Ergebnisse Ihrer Analysen zusammenfassen. Folgende Elemente sollte Ihre Präsentation abdecken:

* **Titelseite**:  Name und Beschreibung der Präsentation, Namen der Autorinnen und Autoren. (1 Folie)
* **Executive Summary**:  Zusammenfassung der Ergebnisse. (1 Folie)
* **Kurzbeschreibung der Methodik**:  Erläuterung der durchgeführten Analysen und der verwendete Datenbasis inklusiver kritischer Würdigung ihres Vorgehens. (3-4 Folien)
* **Vorstellung der Profile**: Nennung der durch die Analysen hergeleiteten Profile mit einem treffenden Namen und einer Kurzbeschreibung je Profil. (1-2 Folien)
* **Detaillierte Profilierung der Cluster**: Detaillierte Analyse der unterschiedlichen Charakteristika der Profile mit Hilfe von Grafiken oder Tabellen zur Erläuterung der Profilnamen, Beschreibungen und Empfehlungen. (je Profil eine Folie)

## Abgabe

Abgabe des Codes in Form eines `*.R` Skripts und der Präsentation als `*.pdf` Datei über ILIAS bis zum **19.01.2023**. 


## Bewerungskriterien

Bewertet werden alle Teile der Abgabe nach folgenden Kriterien:

-   Korrektheit der fachlichen Lösung und Umfang der durchgeführten Analysen
-   Adäquater Einsatz und kritische Reflexion von Methoden und Werkzeugen aus den Vorlesungen
-   Übersichtlichkeit und Nachvollziehbarkeit des eingereichten Codes
-   Strukturierung, Gestaltung und fachliche Korrektheit der Präsentation
-   Einordnung und Relexion der Analyseergebnisse im wirtschaftlichen Kontext

\newpage

## Merkmale des Datensatzes

| ID | Spaltenbezeichnung         | Erläuterung                                                 |
|----|----------------------------|-------------------------------------------------------------|
| 1  | ID                         | Eindeutige Identifikationsnummer des Kreises,               |
|    |                            | bzw. des Bundeslandes.                                      |
| 2  | Kreis                      | Name des Kreises / Bundeslandes.                            |
| 3  | Fläche insgesamt           | Bodenfläche insgesamt des Kreises / Bundeslandes in ha.     |
| 4  | Siedlung                   | Prozentualer Anteil von Siedlungsflächen an der Bodenfläche |  
| 5  | Verkehr                    | Prozentualer Anteil von Verkehrsflächen an der Bodenfläche  |
| 6  | Vegetationsfläche          | Prozentualer Anteil von Vegetationsflächen an der           |
| 7  | Gewässer                   | Prozentualer Anteil von Gewässern an der Bodenfläche        |                     
| 8  | Siedlungsfläche Gesamt     | Gesamte Siedlungsfläche des Kreises / Bundeslandes in ha    |  
| 9  | Wohnbaufläche              | Prozentualer Anteil der Wohnfläche an der Siedlungsfläche   |  
| 10 | Industrie - und            | Prozentualer Anteil der Industrie- und  Gewerbefläche       |
|    | Gewerbefläche              | an der Siedlungsfläche                                      |
| 11 | Halde                      | Prozentualer Anteil der Halde an der Siedlungsfläche        |  
| 12 | Tagebau, Grube, Steinbruch | Prozentualer Anteil von Tagebau, Gruben und Steinbrüche     |
|    |                            | an der Siedlungsfläche                                      |
| 13 | Fläche gemischte Nutzung   | Prozentualer Anteil der gemischten Flächennutzung           |
|    |                            | an der Siedlungsfläche                                      |
| 14 | Fläche besonderer          | Prozentualer Anteil der Flächen mit besonderer funktionaler |
|    | funktionaler Prägung       | Prägung an der Siedlungsfläche                              |
| 15 | Sport-, Freizeit- und      | Prozentualer Anteil der Sport-, Freizeit- und               |
|    | Erholungsfläche            | Erholungsflächen an der Siedlungsfläche                     |
| 16 | Grünanlagen                | Prozentualer Anteil Grünanlagen an der Siedlungsfläche      |
| 17 | Friedhof                   | Prozentualer Anteil an Friedhöfen an der Siedlungsfläche    |
| 18 | Ackerland insgesamt        | Ackerland insgesamt in ha des Kreises / Bundeslandes        |
| 19 | Getreide                   | Prozentualer Anteil Getreideanbau vom Ackerland             |
| 20 | Weizen                     | Prozentualer Anteil Weizenanbau vom Ackerland               |  
| 21 | Winterweizen (einschl.     | Prozentualer Anteil Winterweizenanbau (einschl. Dinker und  |
|    | Dinkel und Einkorn         | Einkorn) vom Ackerland                                      |         
| 22 | Roggen und                 | Prozentualer Anteil Roggen- und Wintermenggetreideanbau     |
|    | Wintermenggetreide         | vom Ackerland                                               |
| 23 | Triticale                  | Prozentualer Anteil Triticaleanbau vom Ackerland            |
| 24 | Gerste                     | Prozentualer Anteil Gerstenanbau vom Ackerland              |
| 25 | Hafer                      | Prozentualer Anteil Haferanbau vom Ackerland                |
| 26 | Körnermais/Corn-Cob-Mix    | Prozentualer Anteil Körnermais/Corn-Cob-Mix Anbau           |
|    |                            | vom Ackerland                                               | 
| 27 | Sonstige Getreide          | Prozentualer Anteil sonstige Getreideanbau vom Ackerland    |
| 28 | Pflanzen zur Grünernte     | Prozentualer Anteil Pflanzen zur Grünernet Anbau am         |
|    |                            | Ackerland                                                   |
| 29 | Silomais/Grünmais          | Prozentualer Anteil Silomais-/Grünmaisanbau vom Ackerland   |
| 30 | Zuckerrüben                | Prozentualer Anteil Zuckerrübenanbau vom Ackerland          |
| 31 | Kartoffeln                 | Prozentualer Anteil Kartoffelanbau vom Ackerland            |
| 32 | Ölfrüchte                  | Prozentualer Anteil Ölfrüchtenanbau vom Ackerland           |
| 33 | Winterraps                 | Prozentualer Anteil Winterrapsanbau vom Ackerland           |
| 34 | Hülsenfrüchte              | Prozentualer Anteil Hülsenfrüchteanbau vom Ackerland        |
| 35 | Niederlassungen            | Niederlassungen insgesamt des Kreises / Bundeslandes        |
| 35 | 0 bis unter 10 abhängig    | Prozentualer Anteil Niederlassungen mit unter 10            |
|    | Beschäftigte               | Beschäftigten                                               |
| 36 | 10 bis unter 50 abhängig   | Prozentualer Anteil Niederlassungen mit 10 bis unter 50     |
|    | Beschäftigte               | Beschäftigten                                               |
| 37 | 50 bis unter 250 abhängig  | Prozentualer Anteil Niederlassungen mit 50 bis unter 250    |
|    | Beschäftigte               | Beschäftigten                                               |
| 38 | 250 und mehr abhängig      | Prozentualer Anteil Niederlassungen 250 und mehr            |
|    | Beschäftigte               | Beschäftigten                                               |
| 39 | Bevölkerung                | Bevölkerung insgesamt pro Kreis / Bundesland                |
| 40 | Wahlberechtigte            | Wahlberechtigte pro Kreis / Bundesland                      |
| 41 | Wahlbeteiligung            | Prozentuale Wahlbeteiligung pro Kreis / Bundesland          |
| 42 | Gültige Zweitstimmen       | Gültige Zweitstimmen pro Kreis / Bundesland                 |
| 43 | CDU/CSU                    | Gültige Zweitstimmen CDU/CSU pro Kreis / Bundesland         |
| 44 | SPD                        | Gültige Zweitstimmen SPD pro Kreis / Bundesland             |
| 45 | Grüne                      | Gültige Zweitstimmen Grüne pro Kreis / Bundesland           |
| 46 | FDP                        | Gültige Zweitstimmen FDP pro Kreis / Bundesland             |
| 47 | DIE LINKE                  | Gültige Zweitstimmen DIE LINKE pro Kreis / Bundesland       |
| 48 | AfD                        | Gültige Zweitstimmen Afd pro Kreis / Bundesland             |
| 49 | Sonstige Partein           | Gültige Zweitstimmen sonstige Partein pro Kreis / Bundesland|
| 50 | Geöffnete                  | Anzahl an geöffneten Beherbergungsbetrieben                 |
|    | Beherbergungsbetriebe      |                                                             |
| 51 | Angebotene                 | Anzahl an Betten zur Übernachtung                           |
|    | Schlafgelegenheiten        |                                                             |
| 52 | Insg. Gästeankünfte        | Insgesamt Gästeänkünfte pro Jahr                            |
| 53 | GA Inland                  | Insgesamt Gästeänkünfte die aus dem Inland kommen           |
| 54 | GA Ausland                 | Insgesamt Gästeänkünfte die aus dem Ausland kommen          |
| 55 | Insg. Gästeübernachtungen  | Insgesamt Gästeübernachtungen pro Jahr                      |
| 56 | GÜ Inland                  | Gästeübernachtungen mit Gästen aus dem Inland               |
| 57 | GÜ Ausland                 | Gästeübernachtungen mit Gästen aus dem Ausland              |



